import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "@/assets/style/tailwind.css";
import "@/assets/style/app.scss";
import SidebarAtm from "@/common/SidebarAtm";
import AdminHeader from "@/common/AdminHeader";

import DynamicSlider from "@/common/DynamicSlider";

const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Atmosphere Living - Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <div className="atmosphere-dashboard">
          <div className="atmosphere-wrapper">
            {/* <SidebarAtm/> */}
           
            <DynamicSlider/>
            <div className="atmosphere-content transition-all pl-[300px]">
              <AdminHeader/>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
